#ifndef CONFIG_H
#define CONFIG_H

#ifndef IS_MCU_VERSION
#define IS_MCU_VERSION 1
#endif

#ifndef KEYCODE_MEM_SIZE
#define KEYCODE_MEM_SIZE 10000
#endif

#ifndef KEY_LED_MAX_BRIGHTNESS
#define KEY_LED_MAX_BRIGHTNESS 100
#endif

#ifndef WALL_AMOUNT_LEDS
#define WALL_AMOUNT_LEDS 462
#endif

#ifndef WALL_LED_HEIGHT_COUNT
#define WALL_LED_HEIGHT_COUNT 7
#endif

#ifndef WALL_LED_MAX_BRIGHTNESS
#define WALL_LED_MAX_BRIGHTNESS 3
#endif

#ifndef CONFIG_FILE_PATH
#define CONFIG_FILE_PATH "/config.json"
#endif

#ifndef DISK_SIZE_MB
#define DISK_SIZE_MB 1
#endif

#ifndef MAX_NUM_LAYERS
#define MAX_NUM_LAYERS 16
#endif

#ifndef AM_MAX_LOOP
#define AM_MAX_LOOP 200
#endif

#ifndef HID_USB_CONNECTION_TIMEOUT
#define HID_USB_CONNECTION_TIMEOUT 1000
#endif

#ifndef LED_WALL_NODE_TEXT_BUFFER_LEN
#define LED_WALL_NODE_TEXT_BUFFER_LEN 15
#endif

#ifndef LED_WALL_NODE_RENDER_BUFFER_LEN
#define LED_WALL_NODE_RENDER_BUFFER_LEN 32
#endif

#endif //CONFIG_H